Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASP.NET_Core_MVC_Piacom.Data;
using ASP.NET_Core_MVC_Piacom.Models.Domain;
using Microsoft.AspNetCore.Authorization;

namespace ASP.NET_Core_MVC_Piacom.Controllers
{
    [Authorize(Roles = "Admin")]

    public class PaymentsController : Controller
    {
        private readonly PiacomDbContext _context;

        public PaymentsController(PiacomDbContext context)
        {
            _context = context;
        }

        // GET: Payments
        public async Task<IActionResult> Index()
        {
            var piacomDbContext = _context.Payments.Include(p => p.Customer);
            return View(await piacomDbContext.ToListAsync());
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .Include(p => p.Customer)
                .FirstOrDefaultAsync(m => m.PaymentID == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // GET: Payments/Create
        public IActionResult Create()
        {
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerName");
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentID,PaymentCode,PaymentDate,Amount,CustomerID,Discount,PaymentStatus")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                payment.PaymentID = Guid.NewGuid();
                _context.Add(payment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerName", payment.CustomerID);
            return View(payment);
        }

        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments.FindAsync(id);
            if (payment == null)
            {
                return NotFound();
            }
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerName", payment.CustomerID);
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("PaymentID,PaymentCode,PaymentDate,Amount,CustomerID,Discount,PaymentStatus")] Payment payment)
        {
            if (id != payment.PaymentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentExists(payment.PaymentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerID"] = new SelectList(_context.Customers, "CustomerID", "CustomerName", payment.CustomerID);
            return View(payment);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .Include(p => p.Customer)
                .FirstOrDefaultAsync(m => m.PaymentID == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var payment = await _context.Payments.FindAsync(id);
            if (payment != null)
            {
                _context.Payments.Remove(payment);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentExists(Guid id)
        {
            return _context.Payments.Any(e => e.PaymentID == id);
        }
    }
}

Controllers/PriceController.cs
using ASP.NET_Core_MVC_Piacom.Data;
using ASP.NET_Core_MVC_Piacom.Models.Domain;
using ASP.NET_Core_MVC_Piacom.Models.ViewModels;
using ASP.NET_Core_MVC_Piacom.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP.NET_Core_MVC_Piacom.Controllers
{
    [Authorize()]

    public class PriceController : Controller
    {
        private readonly IPriceRepository priceRepository;
        private readonly IPriceDetailRepository priceDetailRepository;
        private readonly IProductRepository productRepository;
        private readonly UserManager<IdentityUser> userManager;
        private readonly IUnitRepository unitRepository;

        public PriceController(IPriceRepository priceRepository, IPriceDetailRepository priceDetailRepository,
            IProductRepository productRepository, UserManager<IdentityUser> userManager, IUnitRepository unitRepository )
        {
            this.priceRepository = priceRepository;
            this.priceDetailRepository = priceDetailRepository;
            this.productRepository = productRepository;
            this.userManager = userManager;
            this.unitRepository = unitRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            return View();
        }

        [Authorize(Policy = "CreatePrice")]
        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddPriceRequest addPriceRequest)
        {
            if (!ModelState.IsValid)
            {
                foreach (var state in ModelState)
                {
                    var key = state.Key;
                    var errors = state.Value.Errors;
                    foreach (var error in errors)
                    {
                        // Log the key and error message
                        Console.WriteLine($"Key: {key}, Error: {error.ErrorMessage}");
                    }
                }
                return View(addPriceRequest);
            }
           var currentUser = await userManager.GetUserAsync(User);
            var price = new Price
            {
                PriceCode = addPriceRequest.PriceCode,
                FromDate = addPriceRequest.FromDate,
                ToDate = addPriceRequest.ToDate,
                SysU = currentUser?.UserName,
                SysD = DateTime.Now,
               
            };
            var createdPrice = await priceRepository.AddAsync(price);
            return RedirectToAction("Edit", new { id = createdPrice.PriceID });
        }

        [HttpGet]
        [Authorize(Policy = "ViewPrice")]
        [ActionName("List")]
        public async Task<IActionResult> PriceList()
        {
            var prices = await priceRepository.GetAllAsync();
            return View(prices);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {

            var price = await priceRepository.GetAsync(id);
            var productList = await productRepository.GetAllAsync();
            var unitList = await unitRepository.GetAllAsync();
            var products = productList.Select(p => new SelectListItem
            {
                Value = p.ProductID.ToString(),
                Text = p.ProductName
            }).ToList();
            var units = unitList.Select(u => new SelectListItem
            {
                Value = u.UnitID.ToString(),
                Text = u.UnitName
            });
            if (price == null)
            {
                return NotFound();
            }
            var prices = await priceRepository.GetAllAsync();
            var editPriceRequest = new EditPriceRequest
            {
                PriceID = price.PriceID,
                PriceCode = price.PriceCode,
                FromDate = price.FromDate,
                ToDate = price.ToDate,
                SysU = price.SysU,
                SysD = DateTime.Now,
                PriceDetails = price.PriceDetails?.ToList(),
                Products = products,
                Units = units

            };

            return View(editPriceRequest);
        }

        [HttpPost]
        [Authorize(Policy = "EditPrice")]

        public async Task<IActionResult> Edit(EditPriceRequest editPriceRequest)
        {
            var currentUser = await userManager.GetUserAsync(User);
            if (!ModelState.IsValid)
            {
                foreach (var state in ModelState)
                {
                    var key = state.Key;
                    var errors = state.Value.Errors;
                    foreach (var error in errors)
                    {
                        // Log the key and error message
                        Console.WriteLine($"Key: {key}, Error: {error.ErrorMessage}");
                    }

                }
                var productList = await productRepository.GetAllAsync();
                var unitList = await unitRepository.GetAllAsync();

                editPriceRequest.Products = productList.Select(p => new SelectListItem
                {
                    Value = p.ProductID.ToString(),
                    Text = p.ProductName
                }).ToList();

                editPriceRequest.Units = unitList.Select(u => new SelectListItem
                {
                    Value = u.UnitID.ToString(),
                    Text = u.UnitName
                }).ToList();

                return View(editPriceRequest);
            }
            var price = new Price
            {   
                PriceID = editPriceRequest.PriceID,
                PriceCode = editPriceRequest.PriceCode,
                FromDate = editPriceRequest.FromDate,
                ToDate = editPriceRequest.ToDate,
                SysU = currentUser?.UserName,
                SysD = DateTime.Now,
                PriceDetails = editPriceRequest.PriceDetails ?? new List<PriceDetail>()
            };
            var updatedPriceDetails = editPriceRequest.PriceDetails;
            var existingPriceDetails = price.PriceDetails.ToList();

            var updatedPrice = await priceRepository.UpdateAsync(price);
            if (updatedPrice != null)
            {
                // Show success notification
                return RedirectToAction("List");
            }
            else
            {

                // Show error notification
            }

            return RedirectToAction("Edit", new { id = editPriceRequest.PriceID });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditPriceRequest editPriceRequest)
        {
            var deletedCustomer = await priceRepository.DeleteAsync(editPriceRequest.PriceID);
            if (deletedCustomer != null)
            {
                //show success notification
                return RedirectToAction("List");
            }

            //show error notification

            return RedirectToAction("Edit", new { id = editPriceRequest.PriceID });
        }
    }
}

Controllers/UnitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASP.NET_Core_MVC_Piacom.Data;
using ASP.NET_Core_MVC_Piacom.Models.Domain;
using Microsoft.AspNetCore.Authorization;

namespace ASP.NET_Core_MVC_Piacom.Controllers
{
    [Authorize]

    public class UnitsController : Controller
    {
        private readonly PiacomDbContext _context;

        public UnitsController(PiacomDbContext context)
        {
            _context = context;
        }

        // GET: Units
        [Authorize(Policy = "ViewUnit")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Units.ToListAsync());
        }

        // GET: Units/Details/5
        
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.Units
                .FirstOrDefaultAsync(m => m.UnitID == id);
            if (unit == null)
            {
                return NotFound();
            }

            return View(unit);
        }

        // GET: Units/Create
        [Authorize(Policy ="CreateUnit")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Units/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UnitID,UnitCode,UnitName")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                unit.UnitID = Guid.NewGuid();
                _context.Add(unit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }
        // GET: Units/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.Units.FindAsync(id);
            if (unit == null)
            {
                return NotFound();
            }
            return View(unit);
        }

        // POST: Units/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Policy = "EditUnit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("UnitID,UnitCode,UnitName")] Unit unit)
        {
            if (id != unit.UnitID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(unit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UnitExists(unit.UnitID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }

        // GET: Units/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var unit = await _context.Units
                .FirstOrDefaultAsync(m => m.UnitID == id);
            if (unit == null)
            {
                return NotFound();
            }

            return View(unit);
        }

        // POST: Units/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var unit = await _context.Units.FindAsync(id);

            if (unit == null)
            {
                return NotFound();
            }

            // Check if the unit is referenced in any PriceDetails
            bool isReferenced = await _context.PriceDetails.AnyAsync(pd => pd.UnitID == id);

            if (isReferenced)
            {
                TempData["ErrorMessage"] = "This unit is referenced in price details and cannot be deleted.";
                return RedirectToAction(nameof(Delete), new { id });
            }

            // If not referenced, proceed with deletion
            _context.Units.Remove(unit);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool UnitExists(Guid id)
        {
            return _context.Units.Any(e => e.UnitID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Piacom </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NET_Core_MVC_Piacom.styles.css" asp-append-version="true" />
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            // Function to send a notification
            function sendNotification() {
                const notification = new Notification("Hello!", {
                    body: "You have successfully allowed notifications!",
                    icon: "images/Logo_Piacom.jpg" // Optional: path to an icon image
                });

                notification.onclick = function () {
                    // Action when the notification is clicked
                    window.focus();
                };
            }

            // Check for notification permission
            if (Notification.permission === "default") {
                // Request permission
                Notification.requestPermission().then(function (permission) {
                    if (permission === "granted") {
                        console.log("Notification permission granted.");
                        // Send a notification after permission is granted
                        sendNotification();
                    } else if (permission === "denied") {
                        console.log("Notification permission denied.");
                    }
                })
            };
            // } else if (Notification.permission === "granted") {
            //     // If permission is already granted, send a notification
            //     sendNotification();
            // }
        });
    </script>
</head>
<body>
    <header>
        <nav id="navbar" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Piacom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (signInManager.IsSignedIn(User) || Context.User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            @if (User.IsInRole("SuperAdmin") )
                            {
                                <!-- SuperAdmin specific items -->
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="UserRoles" asp-controller="Account">User Roles</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="AddRoleToUser" asp-controller="Account">Assign Role</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="CreateRole" asp-controller="Account">Create Role</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-action="ViewAllRoles" asp-controller="Account">View All Roles</a>
                                </li>

                            }

                            @if (User.IsInRole("Admin"))
                            {
                                <!-- Admin specific items -->
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuMasterData" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Master Data
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuMasterData">
                                        <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="List">Customers</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Orders" asp-action="List">Orders</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Units" asp-action="Index">Units</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Price" asp-action="List">Prices</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Employees" asp-action="List">Employees</a>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuCustomer" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Customer
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuCustomer">
                                        <a class="dropdown-item" asp-area="" asp-controller="Payments" asp-action="Index">Payments</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="CreditLimit" asp-action="List">Credit Limits</a>
                                    </div>
                                </li>
                            }

                            <!-- Orders Dropdown -->
                            @if (User.HasClaim(c => c.Value.Contains("Orders")))
                            {
                                <li class="nav-item ">
                                    <a class="nav-link" asp-action="List" asp-controller="Orders">Orders</a>
                                </li>
                            }

                            <!-- Products Dropdown -->
                            @if (User.HasClaim(c => c.Value.Contains("Products")))
                            {
                                <li class="nav-item ">
                                    <a class="nav-link" asp-action="Index" asp-controller="Products">Products</a>
                                </li>
                            }

                            <!-- Customers Dropdown -->
                            @if (User.HasClaim(c => c.Value.Contains("Customers")))
                            {
                                    <li class="nav-item ">
                                        <a class="nav-link" asp-action="List" asp-controller="Customer">Customers</a>
                                    </li>
                            }

                            <!-- Prices Dropdown -->
                            @if (User.HasClaim(c => c.Value.Contains("Prices")))
                            {
                                <li class="nav-item ">
                                    <a class="nav-link" asp-action="List" asp-controller="Price">Prices</a>
                                </li>
                            }
                            <!-- Employees Dropdown -->
                            @if (User.HasClaim(c => c.Value.Contains("Employees")))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link" asp-action="List" asp-controller="Employees">Employees</a>
                                </li>
                            }

                            <!-- Units Dropdown -->
                            @if (User.HasClaim(c => c.Value.Contains("Units")))
                            {
                                <li class="nav-item ">
                                    <a class="nav-link" asp-action="Index" asp-controller="Units">Units</a>
                                </li>
                            }

                        </ul>
                    }
                </div>


                <div class="d-flex align-items-center">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <div class="me-3 text-light">
                            @User?.Identity?.Name
                        </div>
                        <a class=" btn me-3 bg-light text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Logout">
                            Logout
                        </a>

                    }
                    else
                    {

                        <a class=" btn me-3 bg-light text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Login">
                            Sign in
                        </a>
                        <a class=" btn me-3 bg-light text-dark"
                           asp-area=""
                           asp-controller="Account"
                           asp-action="Register">
                            Sign up
                        </a>
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ASP.NET_Core_MVC_Piacom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>