Models/Domain/CreditLimit.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASP.NET_Core_MVC_Piacom.Models.Domain;

public class CreditLimit
{
    public Guid CreditLimitID { get; set; } 

    [Required]
    [ForeignKey("Customer")]
    public Guid CustomerID { get; set; }

    [Required]
    public DateTime FromDate { get; set; }

    [Required]
    public DateTime ToDate { get; set; }

    public string? CreditType { get; set; }

    [Required]
    public decimal? Total { get; set; }

    public string? OverDue { get; set; }

    public Customer? Customer { get; set; }
}

Controllers/CreditLimitController.cs
using ASP.NET_Core_MVC_Piacom.Models.Domain;
using ASP.NET_Core_MVC_Piacom.Models.ViewModels;
using ASP.NET_Core_MVC_Piacom.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP.NET_Core_MVC_Piacom.Controllers
{

    [Authorize(Roles = "Admin")]

    public class CreditLimitController : Controller
    {
        private readonly ICreditRepository creditRepository;
        private readonly ICustomerRepository customerRepository;

        public CreditLimitController(ICreditRepository creditRepository, ICustomerRepository customerRepository) 
        {
            this.creditRepository = creditRepository;
            this.customerRepository = customerRepository;
        }

        // GET: Orders
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            // get customer from repository
            var customers = await customerRepository.GetAllAsync();
            var model = new AddCreditRequest
            {
                Customers = customers.Select(c => new SelectListItem
                {
                    Text = c.CustomerName,
                    Value = c.CustomerID.ToString(),

                })
            };
            return View(model);
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddCreditRequest addCreditRequest)
        {
            var credit = new CreditLimit
            {
                CreditLimitID = addCreditRequest.CreditLimitID,
                CustomerID = addCreditRequest.CustomerID,
                FromDate = addCreditRequest.FromDate,
                ToDate = addCreditRequest.ToDate,
                CreditType = addCreditRequest.CreditType,
                OverDue = addCreditRequest.OverDue,
                Total = addCreditRequest.Total,
            };
            await creditRepository.AddAsync(credit);

            return RedirectToAction("List");
        }

        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> Order()
        {
            var credits = await creditRepository.GetAllAsync();
            return View(credits);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var customers = await customerRepository.GetAllAsync();
            var credit = await creditRepository.GetAsync(id);
            if (credit != null)
            {
                var editOrderRequest = new EditCreditRequest
                {
                    CreditLimitID = (Guid)credit.CreditLimitID,
                    CustomerID = credit.CustomerID,
                    FromDate = credit.FromDate,
                    ToDate = credit.ToDate,
                    CreditType = credit.CreditType,
                    Total = credit.Total,
                    OverDue = credit.OverDue,
                    Customers = customers.Select(x => new SelectListItem
                    {
                        Text = x.CustomerName,
                        Value = x.CustomerID.ToString()
                       
                    })
                };
                return View(editOrderRequest);
            }
            return NoContent();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditCreditRequest editCreditRequest)
        {
            var creditLimit = new CreditLimit
            {
                CreditLimitID = editCreditRequest.CreditLimitID,
                CustomerID = editCreditRequest.CustomerID,
                FromDate = editCreditRequest.FromDate,
                ToDate = editCreditRequest.ToDate,
                CreditType = editCreditRequest.CreditType,
                Total = editCreditRequest.Total,
                OverDue = editCreditRequest.OverDue
            };
            var updateCreditLimit = await creditRepository.UpdateAsync(creditLimit);
            if (updateCreditLimit != null)
            {
                // Show success notification
                TempData["SuccessMessage"] = "Credit limit updated successfully.";
                return RedirectToAction("List");
            }
            else
            {
                // Show error notification
                TempData["ErrorMessage"] = "Something went wrong.";
            }

            return RedirectToAction("Edit", new { id = editCreditRequest.CreditLimitID });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditCreditRequest editCreditRequest)
        {
            var deletedCredit = await creditRepository.DeleteAsync(editCreditRequest.CreditLimitID);
            if (deletedCredit != null)
            {
                //show success notification
                return RedirectToAction("List");
            }

            //show error notification

            return RedirectToAction("Edit", new { id = editCreditRequest.CreditLimitID });
        }
    }
}
    

Views/CreditLimit/Add.cshtml
@model ASP.NET_Core_MVC_Piacom.Models.ViewModels.AddCreditRequest

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Add new Credit</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <input type="text" class="form-control" id="creditID" asp-for="CreditLimitID" hidden />

        <div class="row mb-3">
            <div class="col-md-3">
                <label class="form-label">Customer Name</label>
                <select class="form-control short-input" asp-items="@Model.Customers" asp-for="CustomerID">
                </select>
            </div>

            <div class="col-md-3">
                <label class="form-label">From Date</label>
                <input type="date" class="form-control short-input" id="fromDate" asp-for="FromDate" />
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-3">
                <label class="form-label">To Date</label>
                <input type="date" class="form-control short-input" id="toDate" asp-for="ToDate" />
            </div>

            <div class="col-md-3">
                <label class="form-label">Credit Type</label>
                <input type="text" class="form-control short-input" id="creditType" asp-for="CreditType" />
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-3">
                <label class="form-label">Total</label>
                <input type="text" class="form-control short-input" id="total" asp-for="Total" />
            </div>

            <div class="col-md-3">
                <label class="form-label">Overdue</label>
                <input type="text" class="form-control short-input" id="overdue" asp-for="OverDue" />
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
</div>

<style>
    .short-input {
        max-width: 250px; /* Adjust the width as needed */
    }
</style>

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

Views/CreditLimit/Edit.cshtml
@model ASP.NET_Core_MVC_Piacom.Models.ViewModels.EditCreditRequest

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Add new Credit</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <input type="text" class="form-control" id="creditID" asp-for="CreditLimitID" hidden />

        <div class="row mb-3">
            <div class="col-md-3">
                <label class="form-label">Customer Name</label>
                <select class="form-control short-input" asp-items="@Model.Customers" asp-for="CustomerID">
                </select>
            </div>

            <div class="col-md-3">
                <label class="form-label">From Date</label>
                <input type="date" class="form-control short-input" id="fromDate" asp-for="FromDate" />
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-3">
                <label class="form-label">To Date</label>
                <input type="date" class="form-control short-input" id="toDate" asp-for="ToDate" />
            </div>

            <div class="col-md-3">
                <label class="form-label">Credit Type</label>
                <input type="text" class="form-control short-input" id="creditType" asp-for="CreditType" />
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-3">
                <label class="form-label">Total</label>
                <input type="text" class="form-control short-input" id="total" asp-for="Total" />
            </div>

            <div class="col-md-3">
                <label class="form-label">Overdue</label>
                <input type="text" class="form-control short-input" id="overdue" asp-for="OverDue" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="d-flex">
                    <button type="submit" class="btn btn-dark">Update</button>
                    <button type="submit" class="btn btn-danger ms-2" asp-area="" asp-controller="CreditLimit" asp-action="Delete">Delete</button>
                </div>
            </div>
        </div>
    </form>
</div>

<style>
    .short-input {
        max-width: 250px; /* Adjust the width as needed */
    }
</style>

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

Views/CreditLimit/List.cshtml
@model List<ASP.NET_Core_MVC_Piacom.Models.Domain.CreditLimit>
@{
}

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>
            Credit limit List
        </h1>
    </div>
</div>

<a asp-area="" asp-controller="CreditLimit" asp-action="Add">Add Credit Limit</a>

@{
    if(TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["SuccessMessage"]
        </div>
    }
    if(TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["ErrorMessage"]
        </div>
    }
}

<div class="container py-5">
    @if (Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Customer Name</th>
                    <th>From date</th>
                    <th>To date</th>
                    <th>Total</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var credit in Model)
                {
                    <tr>
                        <td>@credit.Customer.CustomerName</td>
                        <td>@credit.FromDate</td>
                        <td>@credit.ToDate</td>
                        <td>@credit.Total</td>
                        <td>
                            <a asp-area="" asp-controller="CreditLimit" asp-action="Edit" asp-route-id="@credit.CreditLimitID">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Credit limit found!</p>
    }
</div>



<!-- Custom inline CSS -->


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>